spring:
  config:
    import: classpath:application-common.yaml
  application:
    name: foodtech-notification-service
  kafka:
    consumer:
      group-id: notification-group

---
# ^^^ Needed to override server.port property from common-module

management:
  server:
    port: 9000