spring:
  application:
    name: api-gateway
  config:
    import: classpath:application-common.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}realms/${keycloak.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      mvc:
        routes:

          - id: order-service-orders-route
            uri: lb://foodtech-order-service
            predicates:
              - Path=/api/orders/**
            filters:
              - StripPrefix=1

          - id: order-service-suborders-route
            uri: lb://foodtech-order-service
            predicates:
              - Path=/api/suborders/**
            filters:
              - StripPrefix=1

          - id: payment-service-route
            uri: lb://foodtech-payment-service
            predicates:
              - Path=/api/payments/**
            filters:
              - StripPrefix=2

          - id: restaurant-service-route
            uri: lb://foodtech-restaurant-service
            predicates:
              - Path=/api/restaurants/**
            filters:
              - StripPrefix=2

keycloak:
#  EnvVar Ov
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8090}
  realm: foodtech
  resource: foodtech-app
  public-client: true

---
# ^^^ Needed to override server.port property from common-module

server:
  port: ${GATEWAY_PORT:8085}

management:
  server:
    port: 8086