spring:
  config:
    import: classpath:application-common.yaml
  application:
    name: foodtech-payment-service
  kafka:
    consumer:
      group-id: payment-group

---
# ^^^ Needed to override properties from application-common

management:
  server:
    port: 9002