server:
  port: 8081

logging:
  level:
    org:
      springframework: WARN

spring:
  application:
    name: foodtech-order-service

  web:
    locale: en_EN
    locale-resolver: fixed

  kafka:
    bootstrap-server: localhost:9092
    consumer:
      bootstrap-servers: ${spring.kafka.bootstrap-server}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: foodtech
      properties:
        spring:
          json:
            trusted:
              packages: com.buoyancy,org.acme,org.springframework
    producer:
      bootstrap-servers: ${spring.kafka.bootstrap-server}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    host: localhost:5432
    database-name: foodtech
    base-url: postgresql://${spring.datasource.host}/${spring.datasource.database-name}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    url: jdbc:${spring.datasource.base-url}
    show-sql: true

  flyway:
    url: jdbc:${spring.datasource.base-url}
    locations: classpath:migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
