spring:
  config:
    import: classpath:application-common.yaml
  application:
    name: foodtech-order-service
  kafka:
    consumer:
      group-id: order-group

---
# ^^^ Needed to override properties from application-common

management:
  server:
    port: 9001