spring:
  config:
    import: classpath:application-common.yaml
  application:
    name: discovery-server

---
# ^^^ Needed to override server.port property from common-module

server:
  #  EnvVar
  port: ${DISCOVERY_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  server:
    port: 8762