spring:
  config:
    import: classpath:application-common.yaml
  application:
    name: discovery-server

---
# ^^^ Needed to override server.port property from common-module

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0