spring:
  config:
    import: classpath:application-common.yaml
  application:
    name: foodtech-restaurant-service
  kafka:
    consumer:
      group-id: restaurant-group

---
# ^^^ Needed to override properties from application-common

management:
  server:
    port: 9003